import 'package:flutter/material.dart';

// وجبات كاملة إضافية
final List<Map<String, dynamic>> completeMealsCategories = [
  {
    'emoji': '🍽️',
    'name': 'وجبات كاملة',
    'color': Colors.deepOrange,
    'imageUrl': null,
    'isLocalImage': false,
    'items': [
      // وجبات إفطار
      {
        'name': 'فطور كامل (بيض + خبز + جبن)',
        'calories': '420',
        'protein': '22',
        'carbs': '35',
        'fat': '22',
      },
      {
        'name': 'فول وطعمية',
        'calories': '380',
        'protein': '18',
        'carbs': '45',
        'fat': '14',
      },
      {
        'name': 'شكشوكة',
        'calories': '290',
        'protein': '16',
        'carbs': '18',
        'fat': '18',
      },
      {
        'name': 'بان كيك بالعسل',
        'calories': '450',
        'protein': '12',
        'carbs': '68',
        'fat': '14',
      },
      {
        'name': 'فرنش توست',
        'calories': '380',
        'protein': '14',
        'carbs': '48',
        'fat': '16',
      },
      {
        'name': 'أومليت بالخضار',
        'calories': '320',
        'protein': '20',
        'carbs': '8',
        'fat': '24',
      },
      {
        'name': 'شوفان بالفواكه والمكسرات',
        'calories': '350',
        'protein': '12',
        'carbs': '52',
        'fat': '12',
      },
      {
        'name': 'كرواسون بالجبن والديك الرومي',
        'calories': '480',
        'protein': '24',
        'carbs': '42',
        'fat': '24',
      },

      // وجبات غداء
      {
        'name': 'كبسة دجاج',
        'calories': '650',
        'protein': '42',
        'carbs': '75',
        'fat': '18',
      },
      {
        'name': 'مندي لحم',
        'calories': '720',
        'protein': '45',
        'carbs': '68',
        'fat': '28',
      },
      {
        'name': 'مقلوبة',
        'calories': '580',
        'protein': '35',
        'carbs': '62',
        'fat': '20',
      },
      {
        'name': 'كشري',
        'calories': '520',
        'protein': '18',
        'carbs': '88',
        'fat': '12',
      },
      {
        'name': 'ملوخية بالأرز',
        'calories': '480',
        'protein': '28',
        'carbs': '58',
        'fat': '16',
      },
      {
        'name': 'محشي ورق عنب',
        'calories': '420',
        'protein': '18',
        'carbs': '52',
        'fat': '16',
      },
      {
        'name': 'كفتة بالطحينة',
        'calories': '550',
        'protein': '38',
        'carbs': '28',
        'fat': '32',
      },
      {
        'name': 'دجاج مشوي مع أرز',
        'calories': '580',
        'protein': '48',
        'carbs': '62',
        'fat': '14',
      },
      {
        'name': 'سمك مشوي مع خضار',
        'calories': '420',
        'protein': '42',
        'carbs': '28',
        'fat': '16',
      },
      {
        'name': 'برياني دجاج',
        'calories': '620',
        'protein': '38',
        'carbs': '72',
        'fat': '20',
      },
      {
        'name': 'مسقعة',
        'calories': '380',
        'protein': '22',
        'carbs': '32',
        'fat': '18',
      },
      {
        'name': 'فتة دجاج',
        'calories': '520',
        'protein': '36',
        'carbs': '48',
        'fat': '20',
      },
      {
        'name': 'شاورما دجاج مع خبز',
        'calories': '580',
        'protein': '42',
        'carbs': '52',
        'fat': '22',
      },
      {
        'name': 'برجر لحم مع بطاطس',
        'calories': '720',
        'protein': '32',
        'carbs': '68',
        'fat': '38',
      },
      {
        'name': 'بيتزا مارجريتا',
        'calories': '620',
        'protein': '28',
        'carbs': '72',
        'fat': '24',
      },
      {
        'name': 'باستا بولونيز',
        'calories': '580',
        'protein': '32',
        'carbs': '68',
        'fat': '20',
      },
      {
        'name': 'لازانيا باللحم',
        'calories': '650',
        'protein': '36',
        'carbs': '58',
        'fat': '28',
      },
      {
        'name': 'ستيك مع بطاطس مهروسة',
        'calories': '680',
        'protein': '48',
        'carbs': '42',
        'fat': '34',
      },
      {
        'name': 'سوشي رول (8 قطع)',
        'calories': '380',
        'protein': '18',
        'carbs': '58',
        'fat': '8',
      },
      {
        'name': 'كاري دجاج مع أرز',
        'calories': '560',
        'protein': '38',
        'carbs': '64',
        'fat': '18',
      },
      {
        'name': 'فاهيتا دجاج',
        'calories': '520',
        'protein': '42',
        'carbs': '48',
        'fat': '18',
      },
      {
        'name': 'تاكو لحم (3 قطع)',
        'calories': '480',
        'protein': '28',
        'carbs': '42',
        'fat': '22',
      },
      {
        'name': 'بوريتو دجاج',
        'calories': '620',
        'protein': '35',
        'carbs': '68',
        'fat': '22',
      },
      {
        'name': 'كباب مشكل مع أرز',
        'calories': '680',
        'protein': '42',
        'carbs': '58',
        'fat': '28',
      },
      {
        'name': 'مظبي دجاج',
        'calories': '640',
        'protein': '40',
        'carbs': '70',
        'fat': '20',
      },
      {
        'name': 'حنيذ لحم',
        'calories': '750',
        'protein': '48',
        'carbs': '65',
        'fat': '32',
      },
      {
        'name': 'مضغوط لحم',
        'calories': '720',
        'protein': '45',
        'carbs': '68',
        'fat': '28',
      },

      // وجبات عشاء خفيفة
      {
        'name': 'سلطة دجاج مشوي',
        'calories': '320',
        'protein': '38',
        'carbs': '18',
        'fat': '12',
      },
      {
        'name': 'شوربة عدس',
        'calories': '180',
        'protein': '12',
        'carbs': '28',
        'fat': '3',
      },
      {
        'name': 'شوربة دجاج بالخضار',
        'calories': '220',
        'protein': '18',
        'carbs': '22',
        'fat': '6',
      },
      {
        'name': 'ساندويتش تونة',
        'calories': '380',
        'protein': '24',
        'carbs': '42',
        'fat': '14',
      },
      {
        'name': 'ساندويتش دجاج مشوي',
        'calories': '420',
        'protein': '32',
        'carbs': '45',
        'fat': '12',
      },
      {
        'name': 'راب دجاج',
        'calories': '450',
        'protein': '28',
        'carbs': '48',
        'fat': '16',
      },
      {
        'name': 'بيض مسلوق مع خبز',
        'calories': '280',
        'protein': '18',
        'carbs': '32',
        'fat': '8',
      },
      {
        'name': 'زبادي بالفواكه والمكسرات',
        'calories': '280',
        'protein': '14',
        'carbs': '38',
        'fat': '10',
      },
      {
        'name': 'شوربة طماطم',
        'calories': '150',
        'protein': '4',
        'carbs': '22',
        'fat': '5',
      },
      {
        'name': 'شوربة خضار',
        'calories': '120',
        'protein': '3',
        'carbs': '20',
        'fat': '3',
      },
      {
        'name': 'شوربة فطر',
        'calories': '180',
        'protein': '6',
        'carbs': '18',
        'fat': '9',
      },
      {
        'name': 'شوربة بصل فرنسية',
        'calories': '220',
        'protein': '8',
        'carbs': '24',
        'fat': '10',
      },

      // وجبات خفيفة (سناك)
      {
        'name': 'ساندويتش جبن مشوي',
        'calories': '380',
        'protein': '18',
        'carbs': '36',
        'fat': '18',
      },
      {
        'name': 'كرواسون بالشوكولاتة',
        'calories': '420',
        'protein': '8',
        'carbs': '48',
        'fat': '22',
      },
      {
        'name': 'مافن بالتوت',
        'calories': '360',
        'protein': '6',
        'carbs': '52',
        'fat': '15',
      },
      {
        'name': 'بيتزا ميني (4 قطع)',
        'calories': '480',
        'protein': '22',
        'carbs': '52',
        'fat': '20',
      },
      {
        'name': 'سمبوسة لحم (4 قطع)',
        'calories': '420',
        'protein': '16',
        'carbs': '38',
        'fat': '24',
      },
      {
        'name': 'سبرينج رول (4 قطع)',
        'calories': '320',
        'protein': '12',
        'carbs': '36',
        'fat': '14',
      },
      {
        'name': 'ناتشوز بالجبن',
        'calories': '520',
        'protein': '14',
        'carbs': '58',
        'fat': '26',
      },
      {
        'name': 'بطاطس ودجز',
        'calories': '380',
        'protein': '6',
        'carbs': '52',
        'fat': '16',
      },
      {
        'name': 'تشيكن ناجتس (6 قطع)',
        'calories': '420',
        'protein': '24',
        'carbs': '28',
        'fat': '22',
      },
      {
        'name': 'موزاريلا ستيكس (6 قطع)',
        'calories': '480',
        'protein': '22',
        'carbs': '32',
        'fat': '28',
      },
      {
        'name': 'أصابع الدجاج (5 قطع)',
        'calories': '380',
        'protein': '26',
        'carbs': '28',
        'fat': '18',
      },
      {
        'name': 'بطاطس محمرة',
        'calories': '320',
        'protein': '4',
        'carbs': '42',
        'fat': '15',
      },
      {
        'name': 'حلقات البصل (8 قطع)',
        'calories': '380',
        'protein': '5',
        'carbs': '42',
        'fat': '21',
      },
      {
        'name': 'كالاماري مقلي',
        'calories': '420',
        'protein': '18',
        'carbs': '32',
        'fat': '24',
      },

      // حلويات
      {
        'name': 'كنافة',
        'calories': '420',
        'protein': '8',
        'carbs': '58',
        'fat': '18',
      },
      {
        'name': 'بسبوسة',
        'calories': '380',
        'protein': '6',
        'carbs': '62',
        'fat': '14',
      },
      {
        'name': 'أم علي',
        'calories': '450',
        'protein': '12',
        'carbs': '58',
        'fat': '20',
      },
      {
        'name': 'مهلبية',
        'calories': '220',
        'protein': '6',
        'carbs': '38',
        'fat': '6',
      },
      {
        'name': 'أرز بالحليب',
        'calories': '280',
        'protein': '8',
        'carbs': '48',
        'fat': '7',
      },
      {
        'name': 'كيك شوكولاتة',
        'calories': '380',
        'protein': '5',
        'carbs': '52',
        'fat': '18',
      },
      {
        'name': 'تشيز كيك',
        'calories': '420',
        'protein': '8',
        'carbs': '42',
        'fat': '26',
      },
      {
        'name': 'تيراميسو',
        'calories': '450',
        'protein': '7',
        'carbs': '48',
        'fat': '26',
      },
      {
        'name': 'براونيز',
        'calories': '380',
        'protein': '5',
        'carbs': '48',
        'fat': '20',
      },
      {
        'name': 'آيس كريم (كوب)',
        'calories': '280',
        'protein': '5',
        'carbs': '36',
        'fat': '14',
      },
      {
        'name': 'بقلاوة',
        'calories': '420',
        'protein': '6',
        'carbs': '52',
        'fat': '22',
      },
      {
        'name': 'قطايف',
        'calories': '320',
        'protein': '5',
        'carbs': '48',
        'fat': '12',
      },
      {
        'name': 'لقمة القاضي',
        'calories': '280',
        'protein': '4',
        'carbs': '42',
        'fat': '12',
      },
    ],
  },
  {
    'emoji': '🥤',
    'name': 'مشروبات',
    'color': Colors.cyan,
    'imageUrl': null,
    'isLocalImage': false,
    'items': [
      // مشروبات ساخنة
      {
        'name': 'قهوة سوداء',
        'calories': '2',
        'protein': '0.3',
        'carbs': '0',
        'fat': '0',
      },
      {
        'name': 'قهوة بالحليب',
        'calories': '38',
        'protein': '2',
        'carbs': '3',
        'fat': '2',
      },
      {
        'name': 'كابتشينو',
        'calories': '80',
        'protein': '4',
        'carbs': '8',
        'fat': '4',
      },
      {
        'name': 'لاتيه',
        'calories': '120',
        'protein': '6',
        'carbs': '10',
        'fat': '6',
      },
      {
        'name': 'موكا',
        'calories': '180',
        'protein': '6',
        'carbs': '24',
        'fat': '7',
      },
      {
        'name': 'شاي أسود',
        'calories': '2',
        'protein': '0',
        'carbs': '0.5',
        'fat': '0',
      },
      {
        'name': 'شاي بالحليب',
        'calories': '35',
        'protein': '1.5',
        'carbs': '4',
        'fat': '1.5',
      },
      {
        'name': 'شاي أخضر',
        'calories': '0',
        'protein': '0',
        'carbs': '0',
        'fat': '0',
      },
      {
        'name': 'نسكافيه',
        'calories': '60',
        'protein': '2',
        'carbs': '10',
        'fat': '1.5',
      },
      {
        'name': 'هوت شوكليت',
        'calories': '220',
        'protein': '8',
        'carbs': '32',
        'fat': '8',
      },
      {
        'name': 'سحلب',
        'calories': '180',
        'protein': '6',
        'carbs': '28',
        'fat': '5',
      },
      {
        'name': 'قرفة ساخنة',
        'calories': '120',
        'protein': '4',
        'carbs': '20',
        'fat': '3',
      },
      {
        'name': 'زنجبيل بالليمون',
        'calories': '25',
        'protein': '0.5',
        'carbs': '6',
        'fat': '0',
      },
      {
        'name': 'يانسون',
        'calories': '15',
        'protein': '0.5',
        'carbs': '3',
        'fat': '0',
      },
      {
        'name': 'كركديه ساخن',
        'calories': '20',
        'protein': '0',
        'carbs': '5',
        'fat': '0',
      },

      // مشروبات باردة
      {
        'name': 'عصير برتقال طبيعي',
        'calories': '112',
        'protein': '1.7',
        'carbs': '26',
        'fat': '0.5',
      },
      {
        'name': 'عصير تفاح',
        'calories': '114',
        'protein': '0.3',
        'carbs': '28',
        'fat': '0.3',
      },
      {
        'name': 'عصير مانجو',
        'calories': '128',
        'protein': '1',
        'carbs': '32',
        'fat': '0.5',
      },
      {
        'name': 'عصير فراولة',
        'calories': '98',
        'protein': '1',
        'carbs': '24',
        'fat': '0.5',
      },
      {
        'name': 'عصير موز بالحليب',
        'calories': '180',
        'protein': '6',
        'carbs': '32',
        'fat': '4',
      },
      {
        'name': 'سموذي فواكه',
        'calories': '220',
        'protein': '4',
        'carbs': '48',
        'fat': '2',
      },
      {
        'name': 'سموذي أخضر',
        'calories': '150',
        'protein': '3',
        'carbs': '32',
        'fat': '1',
      },
      {
        'name': 'ميلك شيك فانيليا',
        'calories': '320',
        'protein': '8',
        'carbs': '48',
        'fat': '12',
      },
      {
        'name': 'ميلك شيك شوكولاتة',
        'calories': '380',
        'protein': '10',
        'carbs': '52',
        'fat': '14',
      },
      {
        'name': 'فرابتشينو',
        'calories': '280',
        'protein': '5',
        'carbs': '42',
        'fat': '10',
      },
      {
        'name': 'آيس كوفي',
        'calories': '120',
        'protein': '3',
        'carbs': '18',
        'fat': '4',
      },
      {
        'name': 'آيس تي',
        'calories': '80',
        'protein': '0',
        'carbs': '20',
        'fat': '0',
      },
      {
        'name': 'ليموناضة',
        'calories': '99',
        'protein': '0.4',
        'carbs': '26',
        'fat': '0.1',
      },
      {
        'name': 'عصير قصب',
        'calories': '180',
        'protein': '0.5',
        'carbs': '45',
        'fat': '0',
      },
      {
        'name': 'تمر هندي',
        'calories': '120',
        'protein': '1',
        'carbs': '30',
        'fat': '0.2',
      },
      {
        'name': 'خروب',
        'calories': '140',
        'protein': '1.5',
        'carbs': '34',
        'fat': '0.3',
      },
      {
        'name': 'سوبيا',
        'calories': '160',
        'protein': '2',
        'carbs': '36',
        'fat': '1',
      },
      {
        'name': 'جلاب',
        'calories': '180',
        'protein': '1',
        'carbs': '44',
        'fat': '0.5',
      },
      {
        'name': 'قمر الدين',
        'calories': '140',
        'protein': '1',
        'carbs': '35',
        'fat': '0.2',
      },
      {
        'name': 'عصير جزر',
        'calories': '94',
        'protein': '2',
        'carbs': '22',
        'fat': '0.4',
      },
      {
        'name': 'عصير بنجر',
        'calories': '70',
        'protein': '2',
        'carbs': '16',
        'fat': '0.2',
      },
      {
        'name': 'عصير أناناس',
        'calories': '132',
        'protein': '0.9',
        'carbs': '33',
        'fat': '0.3',
      },
      {
        'name': 'عصير رمان',
        'calories': '134',
        'protein': '1.5',
        'carbs': '33',
        'fat': '0.7',
      },
      {
        'name': 'عصير جوافة',
        'calories': '112',
        'protein': '2',
        'carbs': '24',
        'fat': '1',
      },

      // مشروبات غازية وطاقة
      {
        'name': 'كولا',
        'calories': '140',
        'protein': '0',
        'carbs': '39',
        'fat': '0',
      },
      {
        'name': 'سفن أب',
        'calories': '140',
        'protein': '0',
        'carbs': '38',
        'fat': '0',
      },
      {
        'name': 'فانتا',
        'calories': '150',
        'protein': '0',
        'carbs': '41',
        'fat': '0',
      },
      {
        'name': 'مشروب طاقة',
        'calories': '110',
        'protein': '0',
        'carbs': '28',
        'fat': '0',
      },
      {
        'name': 'ماء جوز الهند',
        'calories': '46',
        'protein': '1.7',
        'carbs': '9',
        'fat': '0.5',
      },
      {
        'name': 'ماء معدني',
        'calories': '0',
        'protein': '0',
        'carbs': '0',
        'fat': '0',
      },
      {
        'name': 'ماء فوار',
        'calories': '0',
        'protein': '0',
        'carbs': '0',
        'fat': '0',
      },
    ],
  },
  {
    'emoji': '🥜',
    'name': 'مكسرات وبذور',
    'color': Colors.amber,
    'imageUrl': null,
    'isLocalImage': false,
    'items': [
      {
        'name': 'لوز (30g)',
        'calories': '173',
        'protein': '6',
        'carbs': '6',
        'fat': '15',
      },
      {
        'name': 'جوز (30g)',
        'calories': '196',
        'protein': '4.5',
        'carbs': '4',
        'fat': '19',
      },
      {
        'name': 'كاجو (30g)',
        'calories': '166',
        'protein': '5',
        'carbs': '9',
        'fat': '13',
      },
      {
        'name': 'فستق حلبي (30g)',
        'calories': '168',
        'protein': '6',
        'carbs': '8',
        'fat': '13',
      },
      {
        'name': 'بندق (30g)',
        'calories': '188',
        'protein': '4.5',
        'carbs': '5',
        'fat': '18',
      },
      {
        'name': 'فول سوداني (30g)',
        'calories': '170',
        'protein': '8',
        'carbs': '5',
        'fat': '15',
      },
      {
        'name': 'صنوبر (30g)',
        'calories': '202',
        'protein': '4',
        'carbs': '4',
        'fat': '20',
      },
      {
        'name': 'جوز برازيلي (30g)',
        'calories': '197',
        'protein': '4',
        'carbs': '3.5',
        'fat': '20',
      },
      {
        'name': 'جوز بيكان (30g)',
        'calories': '207',
        'protein': '2.7',
        'carbs': '4',
        'fat': '22',
      },
      {
        'name': 'مكاديميا (30g)',
        'calories': '215',
        'protein': '2.4',
        'carbs': '4',
        'fat': '23',
      },
      {
        'name': 'بذور عباد الشمس (30g)',
        'calories': '175',
        'protein': '6',
        'carbs': '6',
        'fat': '15',
      },
      {
        'name': 'بذور اليقطين (30g)',
        'calories': '168',
        'protein': '9',
        'carbs': '3',
        'fat': '15',
      },
      {
        'name': 'بذور الشيا (30g)',
        'calories': '146',
        'protein': '5',
        'carbs': '13',
        'fat': '9',
      },
      {
        'name': 'بذور الكتان (30g)',
        'calories': '160',
        'protein': '5',
        'carbs': '9',
        'fat': '13',
      },
      {
        'name': 'بذور السمسم (30g)',
        'calories': '172',
        'protein': '5',
        'carbs': '7',
        'fat': '15',
      },
      {
        'name': 'طحينة (ملعقة)',
        'calories': '89',
        'protein': '2.6',
        'carbs': '3',
        'fat': '8',
      },
      {
        'name': 'زبدة فول سوداني (ملعقة)',
        'calories': '94',
        'protein': '4',
        'carbs': '3',
        'fat': '8',
      },
      {
        'name': 'زبدة لوز (ملعقة)',
        'calories': '98',
        'protein': '3.4',
        'carbs': '3',
        'fat': '9',
      },
      {
        'name': 'مكسرات مشكلة (30g)',
        'calories': '182',
        'protein': '6',
        'carbs': '6',
        'fat': '16',
      },
      {
        'name': 'تريل ميكس (30g)',
        'calories': '139',
        'protein': '4',
        'carbs': '13',
        'fat': '9',
      },
    ],
  },
];
