import 'package:flutter/material.dart';
import 'complete_meals_data.dart';

final List<Map<String, dynamic>> foodCategories = [
  {
    'emoji': '🍎',
    'name': 'فواكه',
    'color': Colors.red,
    'imageUrl': 'assets/images/فواكهه.png',
    'isLocalImage': true,
    'items': [
      {
        'name': 'تفاح أحمر',
        'calories': '52',
        'protein': '0.3',
        'carbs': '14',
        'fat': '0.2',
      },
      {
        'name': 'تفاح أخضر',
        'calories': '58',
        'protein': '0.4',
        'carbs': '15',
        'fat': '0.2',
      },
      {
        'name': 'موز',
        'calories': '89',
        'protein': '1.1',
        'carbs': '23',
        'fat': '0.3',
      },
      {
        'name': 'برتقال',
        'calories': '47',
        'protein': '0.9',
        'carbs': '12',
        'fat': '0.1',
      },
      {
        'name': 'يوسفي',
        'calories': '53',
        'protein': '0.8',
        'carbs': '13',
        'fat': '0.3',
      },
      {
        'name': 'فراولة',
        'calories': '32',
        'protein': '0.7',
        'carbs': '8',
        'fat': '0.3',
      },
      {
        'name': 'عنب أحمر',
        'calories': '69',
        'protein': '0.7',
        'carbs': '18',
        'fat': '0.2',
      },
      {
        'name': 'عنب أخضر',
        'calories': '69',
        'protein': '0.7',
        'carbs': '18',
        'fat': '0.2',
      },
      {
        'name': 'مانجو',
        'calories': '60',
        'protein': '0.8',
        'carbs': '15',
        'fat': '0.4',
      },
      {
        'name': 'أناناس',
        'calories': '50',
        'protein': '0.5',
        'carbs': '13',
        'fat': '0.1',
      },
      {
        'name': 'كيوي',
        'calories': '61',
        'protein': '1.1',
        'carbs': '15',
        'fat': '0.5',
      },
      {
        'name': 'خوخ',
        'calories': '39',
        'protein': '0.9',
        'carbs': '10',
        'fat': '0.3',
      },
      {
        'name': 'مشمش',
        'calories': '48',
        'protein': '1.4',
        'carbs': '11',
        'fat': '0.4',
      },
      {
        'name': 'كمثرى',
        'calories': '57',
        'protein': '0.4',
        'carbs': '15',
        'fat': '0.1',
      },
      {
        'name': 'بطيخ',
        'calories': '30',
        'protein': '0.6',
        'carbs': '8',
        'fat': '0.2',
      },
      {
        'name': 'شمام',
        'calories': '34',
        'protein': '0.8',
        'carbs': '8',
        'fat': '0.2',
      },
      {
        'name': 'رمان',
        'calories': '83',
        'protein': '1.7',
        'carbs': '19',
        'fat': '1.2',
      },
      {
        'name': 'تين',
        'calories': '74',
        'protein': '0.8',
        'carbs': '19',
        'fat': '0.3',
      },
      {
        'name': 'توت أزرق',
        'calories': '57',
        'protein': '0.7',
        'carbs': '14',
        'fat': '0.3',
      },
      {
        'name': 'توت أسود',
        'calories': '43',
        'protein': '1.4',
        'carbs': '10',
        'fat': '0.5',
      },
      {
        'name': 'كرز',
        'calories': '50',
        'protein': '1',
        'carbs': '12',
        'fat': '0.3',
      },
      {
        'name': 'جوافة',
        'calories': '68',
        'protein': '2.6',
        'carbs': '14',
        'fat': '1',
      },
      {
        'name': 'ليمون',
        'calories': '29',
        'protein': '1.1',
        'carbs': '9',
        'fat': '0.3',
      },
      {
        'name': 'جريب فروت',
        'calories': '42',
        'protein': '0.8',
        'carbs': '11',
        'fat': '0.1',
      },
      {
        'name': 'تمر',
        'calories': '282',
        'protein': '2.5',
        'carbs': '75',
        'fat': '0.4',
      },
      {
        'name': 'باشن فروت',
        'calories': '97',
        'protein': '2.2',
        'carbs': '23',
        'fat': '0.7',
      },
      {
        'name': 'بابايا',
        'calories': '43',
        'protein': '0.5',
        'carbs': '11',
        'fat': '0.3',
      },
      {
        'name': 'ليتشي',
        'calories': '66',
        'protein': '0.8',
        'carbs': '17',
        'fat': '0.4',
      },
      {
        'name': 'تفاح بلدي',
        'calories': '52',
        'protein': '0.3',
        'carbs': '14',
        'fat': '0.2',
      },
      {
        'name': 'برقوق',
        'calories': '46',
        'protein': '0.7',
        'carbs': '11',
        'fat': '0.3',
      },
      {
        'name': 'نكتارين',
        'calories': '44',
        'protein': '1.1',
        'carbs': '11',
        'fat': '0.3',
      },
      {
        'name': 'فراولة مجمدة',
        'calories': '35',
        'protein': '0.7',
        'carbs': '9',
        'fat': '0.3',
      },
      {
        'name': 'توت العليق',
        'calories': '52',
        'protein': '1.2',
        'carbs': '12',
        'fat': '0.7',
      },
      {
        'name': 'جوز هند طازج',
        'calories': '354',
        'protein': '3.3',
        'carbs': '15',
        'fat': '33',
      },
      {
        'name': 'أفوكادو',
        'calories': '160',
        'protein': '2',
        'carbs': '9',
        'fat': '15',
      },
      {
        'name': 'زيتون أخضر',
        'calories': '145',
        'protein': '1',
        'carbs': '4',
        'fat': '15',
      },
      {
        'name': 'زيتون أسود',
        'calories': '115',
        'protein': '0.8',
        'carbs': '6',
        'fat': '11',
      },
      {
        'name': 'كاكا',
        'calories': '70',
        'protein': '0.6',
        'carbs': '19',
        'fat': '0.2',
      },
      {
        'name': 'دراق',
        'calories': '39',
        'protein': '0.9',
        'carbs': '10',
        'fat': '0.3',
      },
      {
        'name': 'سفرجل',
        'calories': '57',
        'protein': '0.4',
        'carbs': '15',
        'fat': '0.1',
      },
      {
        'name': 'فراولة عضوية',
        'calories': '32',
        'protein': '0.7',
        'carbs': '8',
        'fat': '0.3',
      },
      {
        'name': 'موز أحمر',
        'calories': '90',
        'protein': '1.3',
        'carbs': '23',
        'fat': '0.3',
      },
      {
        'name': 'مانجو هندي',
        'calories': '60',
        'protein': '0.8',
        'carbs': '15',
        'fat': '0.4',
      },
      {
        'name': 'عنب بناتي',
        'calories': '69',
        'protein': '0.7',
        'carbs': '18',
        'fat': '0.2',
      },
      {
        'name': 'كمثرى آسيوي',
        'calories': '42',
        'protein': '0.5',
        'carbs': '11',
        'fat': '0.2',
      },
      {
        'name': 'دوريان',
        'calories': '147',
        'protein': '1.5',
        'carbs': '27',
        'fat': '5',
      },
      {
        'name': 'رامبوتان',
        'calories': '68',
        'protein': '0.7',
        'carbs': '16',
        'fat': '0.2',
      },
      {
        'name': 'مانجوستين',
        'calories': '73',
        'protein': '0.4',
        'carbs': '18',
        'fat': '0.6',
      },
      {
        'name': 'ستار فروت',
        'calories': '31',
        'protein': '1',
        'carbs': '7',
        'fat': '0.3',
      },
      {
        'name': 'كرامبولا',
        'calories': '31',
        'protein': '1',
        'carbs': '7',
        'fat': '0.3',
      },
      {
        'name': 'تين شوكي',
        'calories': '41',
        'protein': '0.7',
        'carbs': '10',
        'fat': '0.5',
      },
      {
        'name': 'أكي دنيا',
        'calories': '47',
        'protein': '0.4',
        'carbs': '12',
        'fat': '0.2',
      },
      {
        'name': 'تمر هندي',
        'calories': '239',
        'protein': '2.8',
        'carbs': '63',
        'fat': '0.6',
      },
      {
        'name': 'جاك فروت',
        'calories': '95',
        'protein': '1.7',
        'carbs': '23',
        'fat': '0.6',
      },
    ],
  },
  {
    'emoji': '🥗',
    'name': 'سلطات',
    'color': Colors.green,
    'imageUrl': 'assets/images/سلطات.png',
    'isLocalImage': true,
    'items': [
      {
        'name': 'سلطة خضراء',
        'calories': '15',
        'protein': '1.5',
        'carbs': '3',
        'fat': '0.2',
      },
      {
        'name': 'تبولة',
        'calories': '36',
        'protein': '1.4',
        'carbs': '7',
        'fat': '0.5',
      },
      {
        'name': 'فتوش',
        'calories': '110',
        'protein': '2.5',
        'carbs': '12',
        'fat': '5',
      },
      {
        'name': 'سلطة يونانية',
        'calories': '135',
        'protein': '4',
        'carbs': '8',
        'fat': '9',
      },
      {
        'name': 'سلطة سيزر',
        'calories': '190',
        'protein': '6',
        'carbs': '11',
        'fat': '14',
      },
      {
        'name': 'سلطة تونة',
        'calories': '180',
        'protein': '15',
        'carbs': '6',
        'fat': '11',
      },
      {
        'name': 'سلطة كول سلو',
        'calories': '150',
        'protein': '1.5',
        'carbs': '15',
        'fat': '10',
      },
      {
        'name': 'سلطة بطاطس',
        'calories': '170',
        'protein': '2',
        'carbs': '20',
        'fat': '9',
      },
      {
        'name': 'سلطة معكرونة',
        'calories': '140',
        'protein': '4',
        'carbs': '18',
        'fat': '6',
      },
      {
        'name': 'سلطة الباذنجان',
        'calories': '90',
        'protein': '2',
        'carbs': '12',
        'fat': '4',
      },
      {
        'name': 'بابا غنوج',
        'calories': '120',
        'protein': '3',
        'carbs': '10',
        'fat': '8',
      },
      {
        'name': 'محمرة',
        'calories': '150',
        'protein': '4',
        'carbs': '15',
        'fat': '9',
      },
      {
        'name': 'حمص',
        'calories': '166',
        'protein': '8',
        'carbs': '14',
        'fat': '10',
      },
      {
        'name': 'متبل',
        'calories': '110',
        'protein': '3',
        'carbs': '11',
        'fat': '7',
      },
      {
        'name': 'سلطة الرنجة',
        'calories': '200',
        'protein': '12',
        'carbs': '5',
        'fat': '15',
      },
      {
        'name': 'سلطة الروبيان',
        'calories': '120',
        'protein': '18',
        'carbs': '4',
        'fat': '4',
      },
      {
        'name': 'سلطة نيسواز',
        'calories': '250',
        'protein': '20',
        'carbs': '12',
        'fat': '15',
      },
      {
        'name': 'سلطة كابريزي',
        'calories': '180',
        'protein': '10',
        'carbs': '5',
        'fat': '14',
      },
      {
        'name': 'سلطة والدورف',
        'calories': '200',
        'protein': '3',
        'carbs': '20',
        'fat': '13',
      },
      {
        'name': 'سلطة كوب',
        'calories': '220',
        'protein': '15',
        'carbs': '8',
        'fat': '15',
      },
      {
        'name': 'سلطة الشمندر',
        'calories': '80',
        'protein': '2',
        'carbs': '14',
        'fat': '2',
      },
      {
        'name': 'سلطة الجزر',
        'calories': '60',
        'protein': '1',
        'carbs': '12',
        'fat': '1',
      },
      {
        'name': 'سلطة الكينوا',
        'calories': '160',
        'protein': '6',
        'carbs': '25',
        'fat': '4',
      },
      {
        'name': 'سلطة الحمص',
        'calories': '140',
        'protein': '7',
        'carbs': '22',
        'fat': '3',
      },
      {
        'name': 'سلطة العدس',
        'calories': '150',
        'protein': '9',
        'carbs': '24',
        'fat': '2',
      },
      {
        'name': 'سلطة الفاصوليا',
        'calories': '120',
        'protein': '6',
        'carbs': '20',
        'fat': '2',
      },
      {
        'name': 'سلطة البنجر',
        'calories': '85',
        'protein': '2',
        'carbs': '15',
        'fat': '2',
      },
      {
        'name': 'سلطة الذرة',
        'calories': '100',
        'protein': '3',
        'carbs': '18',
        'fat': '2',
      },
      {
        'name': 'سلطة الأفوكادو',
        'calories': '180',
        'protein': '3',
        'carbs': '10',
        'fat': '15',
      },
      {
        'name': 'سلطة المانجو',
        'calories': '90',
        'protein': '1',
        'carbs': '20',
        'fat': '1',
      },
      {
        'name': 'سلطة الكرنب الأحمر',
        'calories': '45',
        'protein': '2',
        'carbs': '9',
        'fat': '0.5',
      },
      {
        'name': 'سلطة الخيار باللبن',
        'calories': '60',
        'protein': '3',
        'carbs': '8',
        'fat': '2',
      },
      {
        'name': 'سلطة الطحينة',
        'calories': '130',
        'protein': '4',
        'carbs': '8',
        'fat': '10',
      },
      {
        'name': 'سلطة الباذنجان المشوي',
        'calories': '95',
        'protein': '2',
        'carbs': '13',
        'fat': '4',
      },
      {
        'name': 'سلطة الكوسا',
        'calories': '50',
        'protein': '2',
        'carbs': '8',
        'fat': '1',
      },
      {
        'name': 'سلطة الفجل',
        'calories': '30',
        'protein': '1',
        'carbs': '6',
        'fat': '0.3',
      },
      {
        'name': 'سلطة السبانخ',
        'calories': '40',
        'protein': '3',
        'carbs': '5',
        'fat': '1',
      },
      {
        'name': 'سلطة الجرجير',
        'calories': '25',
        'protein': '2',
        'carbs': '3',
        'fat': '0.5',
      },
      {
        'name': 'سلطة الخس',
        'calories': '20',
        'protein': '1',
        'carbs': '4',
        'fat': '0.3',
      },
      {
        'name': 'سلطة الملفوف',
        'calories': '35',
        'protein': '1.5',
        'carbs': '7',
        'fat': '0.2',
      },
      {
        'name': 'سلطة الكرفس',
        'calories': '25',
        'protein': '1',
        'carbs': '5',
        'fat': '0.2',
      },
      {
        'name': 'سلطة الفطر',
        'calories': '45',
        'protein': '3',
        'carbs': '6',
        'fat': '1',
      },
      {
        'name': 'سلطة الباذنجان بالزبادي',
        'calories': '100',
        'protein': '4',
        'carbs': '12',
        'fat': '5',
      },
      {
        'name': 'سلطة الفلفل المشوي',
        'calories': '70',
        'protein': '2',
        'carbs': '12',
        'fat': '2',
      },
      {
        'name': 'سلطة الكرات',
        'calories': '55',
        'protein': '1',
        'carbs': '11',
        'fat': '1',
      },
      {
        'name': 'سلطة السلمون',
        'calories': '220',
        'protein': '22',
        'carbs': '4',
        'fat': '13',
      },
      {
        'name': 'سلطة الدجاج',
        'calories': '180',
        'protein': '20',
        'carbs': '6',
        'fat': '9',
      },
      {
        'name': 'سلطة اللحم',
        'calories': '240',
        'protein': '24',
        'carbs': '5',
        'fat': '15',
      },
      {
        'name': 'سلطة الأرز',
        'calories': '150',
        'protein': '3',
        'carbs': '28',
        'fat': '3',
      },
      {
        'name': 'سلطة البرغل',
        'calories': '110',
        'protein': '4',
        'carbs': '20',
        'fat': '2',
      },
      {
        'name': 'سلطة الفريكة',
        'calories': '120',
        'protein': '5',
        'carbs': '22',
        'fat': '2',
      },
      {
        'name': 'سلطة القمح',
        'calories': '130',
        'protein': '5',
        'carbs': '24',
        'fat': '2',
      },
      {
        'name': 'سلطة الشعير',
        'calories': '125',
        'protein': '4',
        'carbs': '23',
        'fat': '2',
      },
      {
        'name': 'سلطة الكسكس',
        'calories': '140',
        'protein': '5',
        'carbs': '26',
        'fat': '2',
      },
    ],
  },
  {
    'emoji': '🍗',
    'name': 'بروتين',
    'color': Colors.orange,
    'imageUrl': 'assets/images/لحوم.png',
    'isLocalImage': true,
    'items': [
      {
        'name': 'صدر دجاج مشوي',
        'calories': '165',
        'protein': '31',
        'carbs': '0',
        'fat': '3.6',
      },
      {
        'name': 'فخذ دجاج',
        'calories': '209',
        'protein': '26',
        'carbs': '0',
        'fat': '11',
      },
      {
        'name': 'أجنحة دجاج',
        'calories': '203',
        'protein': '30',
        'carbs': '0',
        'fat': '8',
      },
      {
        'name': 'دجاج بالكاري',
        'calories': '180',
        'protein': '25',
        'carbs': '5',
        'fat': '7',
      },
      {
        'name': 'شاورما دجاج',
        'calories': '195',
        'protein': '28',
        'carbs': '3',
        'fat': '8',
      },
      {
        'name': 'سمك سلمون',
        'calories': '206',
        'protein': '22',
        'carbs': '0',
        'fat': '12',
      },
      {
        'name': 'سمك تونة',
        'calories': '132',
        'protein': '28',
        'carbs': '0',
        'fat': '1.3',
      },
      {
        'name': 'سمك بلطي',
        'calories': '128',
        'protein': '26',
        'carbs': '0',
        'fat': '2.7',
      },
      {
        'name': 'سمك موسى',
        'calories': '91',
        'protein': '19',
        'carbs': '0',
        'fat': '1.2',
      },
      {
        'name': 'سمك قاروص',
        'calories': '124',
        'protein': '24',
        'carbs': '0',
        'fat': '2.5',
      },
      {
        'name': 'بيض مسلوق',
        'calories': '155',
        'protein': '13',
        'carbs': '1.1',
        'fat': '11',
      },
      {
        'name': 'بيض مقلي',
        'calories': '196',
        'protein': '13',
        'carbs': '1',
        'fat': '15',
      },
      {
        'name': 'أومليت',
        'calories': '154',
        'protein': '11',
        'carbs': '1',
        'fat': '12',
      },
      {
        'name': 'بيض سكرامبل',
        'calories': '200',
        'protein': '14',
        'carbs': '2',
        'fat': '15',
      },
      {
        'name': 'لحم بقري مشوي',
        'calories': '250',
        'protein': '26',
        'carbs': '0',
        'fat': '15',
      },
      {
        'name': 'لحم عجل',
        'calories': '172',
        'protein': '24',
        'carbs': '0',
        'fat': '8',
      },
      {
        'name': 'كباب لحم',
        'calories': '260',
        'protein': '25',
        'carbs': '2',
        'fat': '17',
      },
      {
        'name': 'كفتة',
        'calories': '280',
        'protein': '23',
        'carbs': '5',
        'fat': '19',
      },
      {
        'name': 'ستيك',
        'calories': '271',
        'protein': '26',
        'carbs': '0',
        'fat': '17',
      },
      {
        'name': 'لحم ضأن',
        'calories': '294',
        'protein': '25',
        'carbs': '0',
        'fat': '21',
      },
      {
        'name': 'كبدة',
        'calories': '175',
        'protein': '27',
        'carbs': '5',
        'fat': '5',
      },
      {
        'name': 'قلب',
        'calories': '160',
        'protein': '26',
        'carbs': '0',
        'fat': '5',
      },
      {
        'name': 'جمبري مشوي',
        'calories': '99',
        'protein': '24',
        'carbs': '0.2',
        'fat': '0.3',
      },
      {
        'name': 'جمبري مقلي',
        'calories': '240',
        'protein': '20',
        'carbs': '10',
        'fat': '14',
      },
      {
        'name': 'كاليماري',
        'calories': '175',
        'protein': '18',
        'carbs': '8',
        'fat': '7',
      },
      {
        'name': 'أخطبوط',
        'calories': '164',
        'protein': '30',
        'carbs': '4',
        'fat': '2',
      },
      {
        'name': 'سرطان البحر',
        'calories': '97',
        'protein': '20',
        'carbs': '0',
        'fat': '1.5',
      },
      {
        'name': 'محار',
        'calories': '68',
        'protein': '7',
        'carbs': '4',
        'fat': '2.5',
      },
      {
        'name': 'بطارخ',
        'calories': '143',
        'protein': '25',
        'carbs': '1.5',
        'fat': '4',
      },
      {
        'name': 'سمك مشوي',
        'calories': '140',
        'protein': '26',
        'carbs': '0',
        'fat': '3',
      },
      {
        'name': 'سمك مقلي',
        'calories': '267',
        'protein': '23',
        'carbs': '12',
        'fat': '15',
      },
      {
        'name': 'فيليه سمك',
        'calories': '112',
        'protein': '23',
        'carbs': '0',
        'fat': '1.5',
      },
      {
        'name': 'تونة معلبة',
        'calories': '128',
        'protein': '26',
        'carbs': '0',
        'fat': '1',
      },
      {
        'name': 'سردين',
        'calories': '208',
        'protein': '25',
        'carbs': '0',
        'fat': '11',
      },
      {
        'name': 'ماكريل',
        'calories': '205',
        'protein': '19',
        'carbs': '0',
        'fat': '14',
      },
      {
        'name': 'أنشوجة',
        'calories': '131',
        'protein': '20',
        'carbs': '0',
        'fat': '5',
      },
      {
        'name': 'لحم ديك رومي',
        'calories': '135',
        'protein': '30',
        'carbs': '0',
        'fat': '1',
      },
      {
        'name': 'بط مشوي',
        'calories': '337',
        'protein': '19',
        'carbs': '0',
        'fat': '28',
      },
      {
        'name': 'أرنب',
        'calories': '173',
        'protein': '33',
        'carbs': '0',
        'fat': '3.5',
      },
      {
        'name': 'حمام',
        'calories': '294',
        'protein': '18',
        'carbs': '0',
        'fat': '24',
      },
      {
        'name': 'سجق',
        'calories': '301',
        'protein': '13',
        'carbs': '1',
        'fat': '27',
      },
      {
        'name': 'بسطرمة',
        'calories': '190',
        'protein': '22',
        'carbs': '2',
        'fat': '11',
      },
      {
        'name': 'لانشون',
        'calories': '250',
        'protein': '12',
        'carbs': '3',
        'fat': '22',
      },
      {
        'name': 'هوت دوج',
        'calories': '290',
        'protein': '10',
        'carbs': '2',
        'fat': '26',
      },
      {
        'name': 'سلامي',
        'calories': '336',
        'protein': '22',
        'carbs': '1',
        'fat': '27',
      },
      {
        'name': 'روست بيف',
        'calories': '150',
        'protein': '25',
        'carbs': '2',
        'fat': '5',
      },
      {
        'name': 'لحم بارد',
        'calories': '140',
        'protein': '23',
        'carbs': '1',
        'fat': '5',
      },
      {
        'name': 'دجاج مدخن',
        'calories': '170',
        'protein': '28',
        'carbs': '1',
        'fat': '6',
      },
      {
        'name': 'سمك مدخن',
        'calories': '117',
        'protein': '18',
        'carbs': '0',
        'fat': '4.5',
      },
      {
        'name': 'توفو',
        'calories': '76',
        'protein': '8',
        'carbs': '2',
        'fat': '4.8',
      },
      {
        'name': 'تمبيه',
        'calories': '193',
        'protein': '19',
        'carbs': '9',
        'fat': '11',
      },
      {
        'name': 'بروتين نباتي',
        'calories': '110',
        'protein': '18',
        'carbs': '5',
        'fat': '2',
      },
      {
        'name': 'سيتان',
        'calories': '370',
        'protein': '75',
        'carbs': '14',
        'fat': '2',
      },
      {
        'name': 'فول مدمس',
        'calories': '187',
        'protein': '12',
        'carbs': '28',
        'fat': '2.5',
      },
    ],
  },
  {
    'emoji': '🥛',
    'name': 'ألبان',
    'color': Colors.blue,
    'imageUrl': 'assets/images/البان.png',
    'isLocalImage': true,
    'items': [
      {
        'name': 'حليب كامل الدسم',
        'calories': '61',
        'protein': '3.2',
        'carbs': '4.8',
        'fat': '3.3',
      },
      {
        'name': 'حليب قليل الدسم',
        'calories': '42',
        'protein': '3.4',
        'carbs': '5',
        'fat': '1',
      },
      {
        'name': 'حليب خالي الدسم',
        'calories': '34',
        'protein': '3.4',
        'carbs': '5',
        'fat': '0.2',
      },
      {
        'name': 'حليب اللوز',
        'calories': '17',
        'protein': '0.6',
        'carbs': '1.5',
        'fat': '1.2',
      },
      {
        'name': 'حليب الصويا',
        'calories': '54',
        'protein': '3.3',
        'carbs': '6',
        'fat': '1.8',
      },
      {
        'name': 'حليب جوز الهند',
        'calories': '230',
        'protein': '2.3',
        'carbs': '6',
        'fat': '24',
      },
      {
        'name': 'زبادي كامل الدسم',
        'calories': '61',
        'protein': '3.5',
        'carbs': '4.7',
        'fat': '3.3',
      },
      {
        'name': 'زبادي قليل الدسم',
        'calories': '59',
        'protein': '10',
        'carbs': '3.6',
        'fat': '0.4',
      },
      {
        'name': 'زبادي يوناني',
        'calories': '97',
        'protein': '9',
        'carbs': '3.6',
        'fat': '5',
      },
      {
        'name': 'لبنة',
        'calories': '88',
        'protein': '7',
        'carbs': '6',
        'fat': '4',
      },
      {
        'name': 'جبن أبيض',
        'calories': '75',
        'protein': '11',
        'carbs': '3',
        'fat': '3',
      },
      {
        'name': 'جبن قريش',
        'calories': '98',
        'protein': '11',
        'carbs': '3.4',
        'fat': '4.3',
      },
      {
        'name': 'جبن شيدر',
        'calories': '403',
        'protein': '25',
        'carbs': '1.3',
        'fat': '33',
      },
      {
        'name': 'جبن موزاريلا',
        'calories': '280',
        'protein': '28',
        'carbs': '2.2',
        'fat': '17',
      },
      {
        'name': 'جبن فيتا',
        'calories': '264',
        'protein': '14',
        'carbs': '4',
        'fat': '21',
      },
      {
        'name': 'جبن بارميزان',
        'calories': '431',
        'protein': '38',
        'carbs': '4',
        'fat': '29',
      },
      {
        'name': 'جبن ريكوتا',
        'calories': '174',
        'protein': '11',
        'carbs': '3',
        'fat': '13',
      },
      {
        'name': 'جبن كريمي',
        'calories': '342',
        'protein': '6',
        'carbs': '4',
        'fat': '34',
      },
      {
        'name': 'قشطة',
        'calories': '195',
        'protein': '2.1',
        'carbs': '3',
        'fat': '20',
      },
      {
        'name': 'كريمة طبخ',
        'calories': '340',
        'protein': '2.2',
        'carbs': '3.5',
        'fat': '36',
      },
      {
        'name': 'كريمة حامضة',
        'calories': '193',
        'protein': '2.4',
        'carbs': '4.6',
        'fat': '19',
      },
      {
        'name': 'زبدة',
        'calories': '717',
        'protein': '0.9',
        'carbs': '0.1',
        'fat': '81',
      },
      {
        'name': 'سمنة بلدي',
        'calories': '900',
        'protein': '0',
        'carbs': '0',
        'fat': '100',
      },
      {
        'name': 'لبن رايب',
        'calories': '60',
        'protein': '3.3',
        'carbs': '4.8',
        'fat': '3.3',
      },
      {
        'name': 'شنينة',
        'calories': '40',
        'protein': '3',
        'carbs': '5',
        'fat': '1',
      },
      {
        'name': 'جبن رومي',
        'calories': '392',
        'protein': '26',
        'carbs': '3',
        'fat': '31',
      },
      {
        'name': 'جبن دمياطي',
        'calories': '272',
        'protein': '17',
        'carbs': '2',
        'fat': '22',
      },
      {
        'name': 'مش',
        'calories': '280',
        'protein': '15',
        'carbs': '3',
        'fat': '23',
      },
      {
        'name': 'جبن استنبولي',
        'calories': '310',
        'protein': '19',
        'carbs': '2',
        'fat': '25',
      },
      {
        'name': 'جبن حلوم',
        'calories': '321',
        'protein': '21',
        'carbs': '2.5',
        'fat': '26',
      },
      {
        'name': 'جبن عكاوي',
        'calories': '290',
        'protein': '18',
        'carbs': '2',
        'fat': '24',
      },
      {
        'name': 'مايونيز',
        'calories': '680',
        'protein': '1',
        'carbs': '1',
        'fat': '75',
      },
      {
        'name': 'حليب مركز محلى',
        'calories': '321',
        'protein': '8',
        'carbs': '54',
        'fat': '8',
      },
      {
        'name': 'حليب مجفف',
        'calories': '496',
        'protein': '26',
        'carbs': '39',
        'fat': '27',
      },
      {
        'name': 'حليب الشوكولاتة',
        'calories': '83',
        'protein': '3.2',
        'carbs': '10',
        'fat': '3.4',
      },
      {
        'name': 'حليب الفانيليا',
        'calories': '80',
        'protein': '3.3',
        'carbs': '9',
        'fat': '3.5',
      },
      {
        'name': 'لبن الزبادي بالفواكه',
        'calories': '90',
        'protein': '4',
        'carbs': '14',
        'fat': '1.5',
      },
      {
        'name': 'زبادي بالعسل',
        'calories': '100',
        'protein': '5',
        'carbs': '15',
        'fat': '2',
      },
      {
        'name': 'كيفير',
        'calories': '61',
        'protein': '3.5',
        'carbs': '4.5',
        'fat': '3.5',
      },
      {
        'name': 'جبن بري',
        'calories': '334',
        'protein': '21',
        'carbs': '0.5',
        'fat': '28',
      },
      {
        'name': 'جبن كممبير',
        'calories': '299',
        'protein': '20',
        'carbs': '0.5',
        'fat': '24',
      },
      {
        'name': 'جبن جورجونزولا',
        'calories': '353',
        'protein': '21',
        'carbs': '2',
        'fat': '29',
      },
      {
        'name': 'جبن إيدام',
        'calories': '357',
        'protein': '25',
        'carbs': '1.4',
        'fat': '28',
      },
      {
        'name': 'جبن غودا',
        'calories': '356',
        'protein': '25',
        'carbs': '2.2',
        'fat': '27',
      },
      {
        'name': 'جبن سويسري',
        'calories': '380',
        'protein': '27',
        'carbs': '5',
        'fat': '28',
      },
      {
        'name': 'جبن بروفولوني',
        'calories': '351',
        'protein': '26',
        'carbs': '2.1',
        'fat': '27',
      },
      {
        'name': 'جبن شيدر مبشور',
        'calories': '403',
        'protein': '25',
        'carbs': '1.3',
        'fat': '33',
      },
      {
        'name': 'جبن كوتاج',
        'calories': '98',
        'protein': '11',
        'carbs': '3.4',
        'fat': '4.3',
      },
      {
        'name': 'جبن ماسكربوني',
        'calories': '429',
        'protein': '4.8',
        'carbs': '4.8',
        'fat': '44',
      },
      {
        'name': 'جبن بانير',
        'calories': '321',
        'protein': '18',
        'carbs': '1.2',
        'fat': '27',
      },
      {
        'name': 'حليب الأرز',
        'calories': '47',
        'protein': '0.3',
        'carbs': '9',
        'fat': '1',
      },
      {
        'name': 'حليب الشوفان',
        'calories': '60',
        'protein': '1.5',
        'carbs': '8',
        'fat': '2.5',
      },
      {
        'name': 'حليب الكاجو',
        'calories': '25',
        'protein': '1',
        'carbs': '1',
        'fat': '2',
      },
      {
        'name': 'زبادي صويا',
        'calories': '72',
        'protein': '4.5',
        'carbs': '7',
        'fat': '3',
      },
      {
        'name': 'جبن نباتي',
        'calories': '280',
        'protein': '1',
        'carbs': '4',
        'fat': '28',
      },
      {
        'name': 'كريمة نباتية',
        'calories': '300',
        'protein': '1',
        'carbs': '6',
        'fat': '30',
      },
      {
        'name': 'زبدة نباتية',
        'calories': '720',
        'protein': '0',
        'carbs': '0',
        'fat': '81',
      },
    ],
  },
  {
    'emoji': '🍞',
    'name': 'حبوب',
    'color': Colors.brown,
    'imageUrl': 'assets/images/حبوب.png',
    'isLocalImage': true,
    'items': [
      {
        'name': 'خبز أبيض',
        'calories': '79',
        'protein': '2.7',
        'carbs': '15',
        'fat': '1',
      },
      {
        'name': 'خبز أسمر',
        'calories': '69',
        'protein': '3.6',
        'carbs': '13',
        'fat': '1',
      },
      {
        'name': 'خبز شعير',
        'calories': '74',
        'protein': '2',
        'carbs': '15',
        'fat': '0.5',
      },
      {
        'name': 'خبز الجاودار',
        'calories': '83',
        'protein': '3.3',
        'carbs': '15',
        'fat': '1.1',
      },
      {
        'name': 'خبز بالحبوب',
        'calories': '65',
        'protein': '3',
        'carbs': '12',
        'fat': '1',
      },
      {
        'name': 'توست أبيض',
        'calories': '79',
        'protein': '2.7',
        'carbs': '15',
        'fat': '1',
      },
      {
        'name': 'توست أسمر',
        'calories': '69',
        'protein': '3.6',
        'carbs': '13',
        'fat': '1',
      },
      {
        'name': 'كرواسون',
        'calories': '406',
        'protein': '8',
        'carbs': '46',
        'fat': '21',
      },
      {
        'name': 'بريوش',
        'calories': '333',
        'protein': '8',
        'carbs': '49',
        'fat': '11',
      },
      {
        'name': 'باجيت',
        'calories': '70',
        'protein': '2.7',
        'carbs': '14',
        'fat': '0.5',
      },
      {
        'name': 'أرز أبيض',
        'calories': '130',
        'protein': '2.7',
        'carbs': '28',
        'fat': '0.3',
      },
      {
        'name': 'أرز بني',
        'calories': '111',
        'protein': '2.6',
        'carbs': '23',
        'fat': '0.9',
      },
      {
        'name': 'أرز بسمتي',
        'calories': '121',
        'protein': '3',
        'carbs': '25',
        'fat': '0.4',
      },
      {
        'name': 'أرز ياسمين',
        'calories': '129',
        'protein': '2.9',
        'carbs': '28',
        'fat': '0.2',
      },
      {
        'name': 'معكرونة بيضاء',
        'calories': '131',
        'protein': '5',
        'carbs': '25',
        'fat': '1.1',
      },
      {
        'name': 'معكرونة بنية',
        'calories': '124',
        'protein': '5.3',
        'carbs': '26',
        'fat': '0.5',
      },
      {
        'name': 'سباغيتي',
        'calories': '158',
        'protein': '6',
        'carbs': '31',
        'fat': '0.9',
      },
      {
        'name': 'لازانيا',
        'calories': '135',
        'protein': '5',
        'carbs': '26',
        'fat': '1.2',
      },
      {
        'name': 'بيني',
        'calories': '131',
        'protein': '5',
        'carbs': '25',
        'fat': '1.1',
      },
      {
        'name': 'فارفالي',
        'calories': '131',
        'protein': '5',
        'carbs': '25',
        'fat': '1.1',
      },
      {
        'name': 'شوفان',
        'calories': '68',
        'protein': '2.4',
        'carbs': '12',
        'fat': '1.4',
      },
      {
        'name': 'كورن فليكس',
        'calories': '357',
        'protein': '7',
        'carbs': '84',
        'fat': '0.9',
      },
      {
        'name': 'جرانولا',
        'calories': '471',
        'protein': '12',
        'carbs': '54',
        'fat': '22',
      },
      {
        'name': 'ميوزلي',
        'calories': '352',
        'protein': '10',
        'carbs': '66',
        'fat': '5',
      },
      {
        'name': 'كينوا',
        'calories': '120',
        'protein': '4.4',
        'carbs': '21',
        'fat': '1.9',
      },
      {
        'name': 'برغل',
        'calories': '83',
        'protein': '3',
        'carbs': '19',
        'fat': '0.2',
      },
      {
        'name': 'فريكة',
        'calories': '95',
        'protein': '3.5',
        'carbs': '20',
        'fat': '0.5',
      },
      {
        'name': 'كسكس',
        'calories': '112',
        'protein': '3.8',
        'carbs': '23',
        'fat': '0.2',
      },
      {
        'name': 'فريك',
        'calories': '95',
        'protein': '3.5',
        'carbs': '20',
        'fat': '0.5',
      },
      {
        'name': 'ذرة مسلوقة',
        'calories': '86',
        'protein': '3.2',
        'carbs': '19',
        'fat': '1.2',
      },
      {
        'name': 'ذرة مشوية',
        'calories': '86',
        'protein': '3.2',
        'carbs': '19',
        'fat': '1.2',
      },
      {
        'name': 'بطاطس مسلوقة',
        'calories': '87',
        'protein': '2',
        'carbs': '20',
        'fat': '0.1',
      },
      {
        'name': 'بطاطس مشوية',
        'calories': '93',
        'protein': '2.5',
        'carbs': '21',
        'fat': '0.1',
      },
      {
        'name': 'بطاطا حلوة',
        'calories': '86',
        'protein': '1.6',
        'carbs': '20',
        'fat': '0.1',
      },
      {
        'name': 'كسافا',
        'calories': '160',
        'protein': '1.4',
        'carbs': '38',
        'fat': '0.3',
      },
      {
        'name': 'كيك',
        'calories': '257',
        'protein': '4',
        'carbs': '42',
        'fat': '9',
      },
      {
        'name': 'دونات',
        'calories': '452',
        'protein': '5',
        'carbs': '51',
        'fat': '25',
      },
      {
        'name': 'مافن',
        'calories': '377',
        'protein': '6',
        'carbs': '51',
        'fat': '17',
      },
      {
        'name': 'بسكويت سادة',
        'calories': '502',
        'protein': '6',
        'carbs': '64',
        'fat': '25',
      },
      {
        'name': 'بسكويت شوكولاتة',
        'calories': '524',
        'protein': '6',
        'carbs': '67',
        'fat': '27',
      },
      {
        'name': 'كراكرز',
        'calories': '503',
        'protein': '9',
        'carbs': '64',
        'fat': '23',
      },
      {
        'name': 'بريتزل',
        'calories': '381',
        'protein': '10',
        'carbs': '80',
        'fat': '3',
      },
      {
        'name': 'شيبس',
        'calories': '536',
        'protein': '7',
        'carbs': '53',
        'fat': '34',
      },
      {
        'name': 'فشار',
        'calories': '387',
        'protein': '12',
        'carbs': '78',
        'fat': '4',
      },
      {
        'name': 'رقائق ذرة',
        'calories': '357',
        'protein': '7',
        'carbs': '84',
        'fat': '0.9',
      },
      {
        'name': 'نودلز',
        'calories': '138',
        'protein': '4.5',
        'carbs': '26',
        'fat': '2',
      },
      {
        'name': 'رامن',
        'calories': '188',
        'protein': '5',
        'carbs': '27',
        'fat': '7',
      },
      {
        'name': 'أودون',
        'calories': '99',
        'protein': '3',
        'carbs': '21',
        'fat': '0.5',
      },
      {
        'name': 'سوبا',
        'calories': '99',
        'protein': '5',
        'carbs': '21',
        'fat': '0.1',
      },
      {
        'name': 'باستا مع صلصة',
        'calories': '160',
        'protein': '5.5',
        'carbs': '30',
        'fat': '2',
      },
      {
        'name': 'ريزوتو',
        'calories': '143',
        'protein': '3.5',
        'carbs': '23',
        'fat': '4',
      },
      {
        'name': 'بيلاف',
        'calories': '158',
        'protein': '3',
        'carbs': '30',
        'fat': '3',
      },
      {
        'name': 'بيتزا عجينة',
        'calories': '266',
        'protein': '11',
        'carbs': '33',
        'fat': '10',
      },
    ],
  },
  {
    'emoji': '🥕',
    'name': 'خضروات',
    'color': Colors.lightGreen,
    'imageUrl': 'assets/images/سلطه.png',
    'isLocalImage': true,
    'items': [
      {
        'name': 'جزر',
        'calories': '41',
        'protein': '0.9',
        'carbs': '10',
        'fat': '0.2',
      },
      {
        'name': 'بروكلي',
        'calories': '34',
        'protein': '2.8',
        'carbs': '7',
        'fat': '0.4',
      },
      {
        'name': 'قرنبيط',
        'calories': '25',
        'protein': '1.9',
        'carbs': '5',
        'fat': '0.3',
      },
      {
        'name': 'طماطم',
        'calories': '18',
        'protein': '0.9',
        'carbs': '3.9',
        'fat': '0.2',
      },
      {
        'name': 'خيار',
        'calories': '15',
        'protein': '0.7',
        'carbs': '3.6',
        'fat': '0.1',
      },
      {
        'name': 'فلفل أخضر',
        'calories': '20',
        'protein': '0.9',
        'carbs': '4.6',
        'fat': '0.2',
      },
      {
        'name': 'فلفل أحمر',
        'calories': '31',
        'protein': '1',
        'carbs': '6',
        'fat': '0.3',
      },
      {
        'name': 'فلفل أصفر',
        'calories': '27',
        'protein': '1',
        'carbs': '6.3',
        'fat': '0.2',
      },
      {
        'name': 'سبانخ',
        'calories': '23',
        'protein': '2.9',
        'carbs': '3.6',
        'fat': '0.4',
      },
      {
        'name': 'خس',
        'calories': '15',
        'protein': '1.4',
        'carbs': '2.9',
        'fat': '0.2',
      },
      {
        'name': 'جرجير',
        'calories': '25',
        'protein': '2.6',
        'carbs': '3.7',
        'fat': '0.7',
      },
      {
        'name': 'كرنب',
        'calories': '25',
        'protein': '1.3',
        'carbs': '6',
        'fat': '0.1',
      },
      {
        'name': 'ملفوف أحمر',
        'calories': '31',
        'protein': '1.4',
        'carbs': '7.4',
        'fat': '0.2',
      },
      {
        'name': 'باذنجان',
        'calories': '25',
        'protein': '1',
        'carbs': '6',
        'fat': '0.2',
      },
      {
        'name': 'كوسا',
        'calories': '17',
        'protein': '1.2',
        'carbs': '3.1',
        'fat': '0.3',
      },
      {
        'name': 'فاصوليا خضراء',
        'calories': '31',
        'protein': '1.8',
        'carbs': '7',
        'fat': '0.2',
      },
      {
        'name': 'بازلاء',
        'calories': '81',
        'protein': '5.4',
        'carbs': '14',
        'fat': '0.4',
      },
      {
        'name': 'بامية',
        'calories': '33',
        'protein': '1.9',
        'carbs': '7.5',
        'fat': '0.2',
      },
      {
        'name': 'ملوخية',
        'calories': '37',
        'protein': '3.3',
        'carbs': '6.5',
        'fat': '0.6',
      },
      {
        'name': 'كرفس',
        'calories': '14',
        'protein': '0.7',
        'carbs': '3',
        'fat': '0.2',
      },
      {
        'name': 'فجل',
        'calories': '16',
        'protein': '0.7',
        'carbs': '3.4',
        'fat': '0.1',
      },
      {
        'name': 'لفت',
        'calories': '28',
        'protein': '0.9',
        'carbs': '6.4',
        'fat': '0.1',
      },
      {
        'name': 'شمندر',
        'calories': '43',
        'protein': '1.6',
        'carbs': '10',
        'fat': '0.2',
      },
      {
        'name': 'بصل',
        'calories': '40',
        'protein': '1.1',
        'carbs': '9.3',
        'fat': '0.1',
      },
      {
        'name': 'ثوم',
        'calories': '149',
        'protein': '6.4',
        'carbs': '33',
        'fat': '0.5',
      },
      {
        'name': 'كراث',
        'calories': '61',
        'protein': '1.5',
        'carbs': '14',
        'fat': '0.3',
      },
      {
        'name': 'بصل أخضر',
        'calories': '32',
        'protein': '1.8',
        'carbs': '7.3',
        'fat': '0.2',
      },
      {
        'name': 'فجل أبيض',
        'calories': '18',
        'protein': '0.6',
        'carbs': '4.1',
        'fat': '0.1',
      },
      {
        'name': 'خرشوف',
        'calories': '47',
        'protein': '3.3',
        'carbs': '11',
        'fat': '0.2',
      },
      {
        'name': 'كرنب بروكسل',
        'calories': '43',
        'protein': '3.4',
        'carbs': '9',
        'fat': '0.3',
      },
      {
        'name': 'هليون',
        'calories': '20',
        'protein': '2.2',
        'carbs': '3.9',
        'fat': '0.1',
      },
      {
        'name': 'فطر',
        'calories': '22',
        'protein': '3.1',
        'carbs': '3.3',
        'fat': '0.3',
      },
      {
        'name': 'ذرة صفراء',
        'calories': '86',
        'protein': '3.2',
        'carbs': '19',
        'fat': '1.2',
      },
      {
        'name': 'كرات',
        'calories': '61',
        'protein': '1.5',
        'carbs': '14',
        'fat': '0.3',
      },
      {
        'name': 'جنزبيل',
        'calories': '80',
        'protein': '1.8',
        'carbs': '18',
        'fat': '0.8',
      },
      {
        'name': 'كزبرة خضراء',
        'calories': '23',
        'protein': '2.1',
        'carbs': '3.7',
        'fat': '0.5',
      },
      {
        'name': 'بقدونس',
        'calories': '36',
        'protein': '3',
        'carbs': '6.3',
        'fat': '0.8',
      },
      {
        'name': 'شبت',
        'calories': '43',
        'protein': '3.5',
        'carbs': '7',
        'fat': '1.1',
      },
      {
        'name': 'نعناع',
        'calories': '70',
        'protein': '3.8',
        'carbs': '15',
        'fat': '0.9',
      },
      {
        'name': 'ريحان',
        'calories': '23',
        'protein': '3.2',
        'carbs': '2.7',
        'fat': '0.6',
      },
      {
        'name': 'كركديه',
        'calories': '37',
        'protein': '0.4',
        'carbs': '9',
        'fat': '0.1',
      },
      {
        'name': 'قلقاس',
        'calories': '112',
        'protein': '1.5',
        'carbs': '27',
        'fat': '0.2',
      },
      {
        'name': 'يقطين',
        'calories': '26',
        'protein': '1',
        'carbs': '6.5',
        'fat': '0.1',
      },
      {
        'name': 'كوسا صفراء',
        'calories': '18',
        'protein': '1.5',
        'carbs': '3',
        'fat': '0.3',
      },
      {
        'name': 'خيار مخلل',
        'calories': '11',
        'protein': '0.3',
        'carbs': '2.3',
        'fat': '0.2',
      },
      {
        'name': 'زيتون مخلل',
        'calories': '115',
        'protein': '0.8',
        'carbs': '6',
        'fat': '11',
      },
      {
        'name': 'مخلل مشكل',
        'calories': '12',
        'protein': '0.5',
        'carbs': '2.5',
        'fat': '0.1',
      },
      {
        'name': 'طرشي',
        'calories': '15',
        'protein': '0.6',
        'carbs': '3',
        'fat': '0.2',
      },
      {
        'name': 'جزر مخلل',
        'calories': '25',
        'protein': '0.5',
        'carbs': '5',
        'fat': '0.1',
      },
      {
        'name': 'فلفل محشي',
        'calories': '80',
        'protein': '2',
        'carbs': '15',
        'fat': '2',
      },
      {
        'name': 'ورق عنب',
        'calories': '93',
        'protein': '6',
        'carbs': '18',
        'fat': '1',
      },
      {
        'name': 'كرنب محشي',
        'calories': '115',
        'protein': '7',
        'carbs': '15',
        'fat': '4',
      },
      {
        'name': 'باذنجان محشي',
        'calories': '120',
        'protein': '6',
        'carbs': '18',
        'fat': '3',
      },
    ],
  },
  ...completeMealsCategories, // إضافة الوجبات الكاملة والمشروبات والمكسرات
];
